### ISSUE TITLE
Fork requests

### ISSUE THREAD

**Issue by gsunsnackv** [kasketis/netfox#148]
Our app uses a few 3rd party SDKs like AppsFlyer, Facebook Analytics, Firebase Analytics, etc, that send data to their services. Is it possible to capture those requests and send a copy to our own backend using netfox?

**Comment by felipeflorencio** [comment]
Hey @gsunsnackv I understand your need, but the thing is, the framework it self does not intercept the iPhone network layer itself, what we do is, when we have a connection using NSURLSession we act as a "proxy" and we can see all the request's, but we just see and let things continue.

3rd party SDK implement their own connections, and it's framework and they don't expose this layer by obvious reasons like security, so, as we can't intercept that and we do not have  access to their connections there's no way to provide this.

The only way is you use a proxy tool like Charles or MITMProxy in order to do this, and this can lead to question like do they have "certificate pinning"? And if yes you will need a little more effort in order to get this, but google can help you for this.

Tnx, closing this issue, any question let me know.
