### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by Janglinator** [kasketis/netfox#95]
More of a mental note, but we should be using encryption in our storage of these request bodies, if we're not already.

**Comment by felipeflorencio** [comment]
Do you have any propose about where should encrypt ? Even more, as it's suppose to have this library being used only for development needs you should't even archive this library in your project when releasing, and for this you have some environment configuration's that you can drop from archive.

**Comment by Janglinator** [comment]
I definitely agree, it was more of a proposal than an actual feature request  :)

However we're taking would-be encrypted network traffic (using https) is recorded and storing it in a non-encrypted way.  While this theoretically *should* never be used in a release, we're leaving the window WIDE open to expose sensitive data

**Comment by felipeflorencio** [comment]
Yeap indeed, I believe this is something that should be looked into but on another perspective, I thing the library itself the purpose is to intercept / log / and share, beside this should be expose for user handle saving the data maybe?
Because when it's about save or not we could end up with different ways but imagine that we are handling upload's or download, some request's could be very big, that will slow down and use too much resource for save, and change from type to type.
And we have the thing about saving encrypted, this is another thing that use a lot of resources too, some times slow down significantly, I thing in a situation that we have multiple request's happening.
One way to "by pass" this would be handle data inside a queue, that would not be the best as we will left non-encrypted data on memory that could be read, and add another complexity layer to handle.
 
But I will look more into to validate some ideas and see if we can achieve this in a good way about security and not slow down using too much resources

**Comment by Janglinator** [comment]
Yeah that's my biggest concern, the potential to slow down data retrieval.  That, and whether the benefits even outweigh the time required to write the encryption  :P

**Comment by vGubriienko** [comment]
Moved to project.
